Use Customer_Support_DeepTech_analysis;
Go;

-- CHECK WHICH DATABASE IS IN USE --
SELECT DB_NAME() AS CurrentDatabase;

-- CHECK / UNDERSTAND THE DATA IN THE TABLES
SELECT *
FROM Survey_table;

SELECT *
FROM Case_table;

-- COUNT THE NUMBER OF ITEMS IN THE TABLE --
SELECT COUNT(*) AS Total_count
FROM Case_table;

SELECT COUNT(*) AS Total_count
FROM Survey_table;

-- 3 Data Profiling --

-- for case table
SELECT
    COUNT(*) AS Total_Rows,

    SUM(CASE WHEN CASE_FIRST_OUTSOURCE_VENDOR_NAME IS NULL THEN 1 ELSE 0 END) AS Null_Vendor,

    SUM(CASE WHEN CASE_CS_FIRST_EMPLOYEE_SUPPORT_TYPE IS NULL THEN 1 ELSE 0 END) AS Null_Employee_Type,

    SUM(CASE WHEN CASE_CS_FIRST_EMPLOYEE_IS_NEWBIE IS NULL THEN 1 ELSE 0 END) AS Null_Newbie,

    SUM(CASE WHEN CASE_TOTAL_NET_HANDLING_TIME_MINUTES IS NULL THEN 1 ELSE 0 END) AS Null_Net_Handling_Time,

    SUM(CASE WHEN CASE_TOTAL_HANDLING_TIME_MINUTES IS NULL THEN 1 ELSE 0 END) AS Null_Total_Handling_Time

FROM Case_table;

-- for survey table
SELECT
    COUNT(*) AS Total_Rows,

    SUM(CASE WHEN SURVEY_SOLVED_ISSUE IS NULL THEN 1 ELSE 0 END) AS Null_Solved_Issue,

    SUM(CASE WHEN SURVEY_DATE_SENT IS NULL THEN 1 ELSE 0 END) AS Null_Date_Sent

FROM Survey_table;


-- 4 Handle Missing --

-- Vendor Column
UPDATE Case_table
SET CASE_FIRST_OUTSOURCE_VENDOR_NAME = 'Not Outsourced'
WHERE CASE_FIRST_OUTSOURCE_VENDOR_NAME IS NULL;

-- Employee Column
UPDATE Case_table
SET CASE_CS_FIRST_EMPLOYEE_SUPPORT_TYPE = 'Uknown'
WHERE CASE_CS_FIRST_EMPLOYEE_SUPPORT_TYPE IS NULL;

-- Newbie Column
UPDATE Case_table
SET CASE_CS_FIRST_EMPLOYEE_IS_NEWBIE = 0
WHERE CASE_CS_FIRST_EMPLOYEE_IS_NEWBIE IS NULL;

-- Handling Time (Median)

-- Get the Median FOR TOATAL NET HANDLING TIME MINUTES First
SELECT
PERCENTILE_CONT(0.5)
WITHIN GROUP (ORDER BY CASE_TOTAL_NET_HANDLING_TIME_MINUTES)
OVER () AS Median_Value
FROM Case_table;

UPDATE Case_table
SET CASE_TOTAL_NET_HANDLING_TIME_MINUTES = 16.9833335876465
WHERE CASE_TOTAL_NET_HANDLING_TIME_MINUTES IS NULL;

-- GET MEDIAN FOR CASE TOTAL HANDLING TIME MINUTES
SELECT
PERCENTILE_CONT(0.5)
WITHIN GROUP (ORDER BY CASE_TOTAL_HANDLING_TIME_MINUTES)
OVER () AS Median_Handiling_Value
FROM Case_table;

UPDATE Case_table
SET CASE_TOTAL_HANDLING_TIME_MINUTES = 17.3500003814697
WHERE CASE_TOTAL_HANDLING_TIME_MINUTES IS NULL;

-- CONFIRM CLEANING WORKED
SELECT
SUM(CASE WHEN CASE_TOTAL_NET_HANDLING_TIME_MINUTES IS NULL THEN 1 ELSE 0 END) AS NetHandling_Nulls,
SUM(CASE WHEN CASE_FIRST_OUTSOURCE_VENDOR_NAME IS NULL THEN 1 ELSE 0 END) AS Vendor_Nulls
FROM Case_table;

--5  CREATE JOINED DATA SET --
CREATE VIEW joined_table AS
SELECT
    s.CASE_ID,
    s.SURVEY_SOLVED_ISSUE,
    s.SURVEY_DATE_SENT,

    c.CASE_CREATION_DATE,
    c.CASE_FIRST_OUTSOURCE_VENDOR_NAME,
    c.CASE_CS_FIRST_OFFICE_LOCATION,
    c.CASE_CS_FIRST_EMPLOYEE_IS_NEWBIE,
    c.CASE_CS_FIRST_EMPLOYEE_SUPPORT_TYPE,
    c.CASE_HAS_QUICK_REPLY,
    c.CASE_IS_FCR,
    c.CASE_CONTACT_COUNT,
    c.CASE_END_TO_END_RESOLUTION_TIME_MINUTES,
    c.CASE_TOTAL_HANDLING_TIME_MINUTES,
    c.CASE_TOTAL_NET_HANDLING_TIME_MINUTES,
    c.CASE_HAS_ESCALATION,
    c.CASE_HAS_L2_OR_NATIVE_ESCALATION,
    c.CASE_HAS_NON_CS_ESCALATION

FROM Survey_table s
JOIN Case_table c
ON s.CASE_ID = c.CASE_ID;

-- TO TEST THE JOINED TABLE
SELECT TOP 10 * FROM joined_table;

-- 6 Analysis Queries --
-- i Resolution Rate
SELECT
ROUND(
	SUM(CASE WHEN SURVEY_SOLVED_ISSUE = 1 THEN 1 ELSE 0 END) * 100.0 
	/ COUNT(*), 2) AS Resolution_Rate
FROM joined_table;

-- ii Resolution VS Contact Count
SELECT
CASE_CONTACT_COUNT,
AVG(CASE WHEN SURVEY_SOLVED_ISSUE = 1 THEN 1.0 ELSE 0 END) * 100 AS Resolution_Rate
FROM joined_table
GROUP BY CASE_CONTACT_COUNT
ORDER BY CASE_CONTACT_COUNT;

-- iii Resolution VS FCR
SELECT 
CASE_IS_FCR,
AVG(CASE WHEN SURVEY_SOLVED_ISSUE = 1 THEN 1.0 ELSE 0 END)* 100 AS Resolution_Rate
FROM joined_table
GROUP BY CASE_IS_FCR;

-- iv Resolution VS Escalation
SELECT 
CASE_HAS_ESCALATION,
AVG(CASE WHEN SURVEY_SOLVED_ISSUE = 1 THEN 1.0 ELSE 0 END) * 100 AS Resolution_Rate
FROM joined_table
GROUP BY CASE_HAS_ESCALATION;

-- v Resolution VS Handling Time Group
SELECT
CASE
WHEN CASE_TOTAL_NET_HANDLING_TIME_MINUTES < 10 THEN '0 - 10'
WHEN CASE_TOTAL_NET_HANDLING_TIME_MINUTES < 30 THEN '10 - 30'
WHEN CASE_TOTAL_NET_HANDLING_TIME_MINUTES < 60 THEN '30 - 60'
ELSE '60+'
END AS Time_Group,

AVG(CASE WHEN SURVEY_SOLVED_ISSUE = 1 THEN 1.0 ELSE 0 END) * 100 AS Resolution_Rate

FROM joined_table
GROUP BY
CASE
WHEN CASE_TOTAL_NET_HANDLING_TIME_MINUTES < 10 THEN '0 - 10'
WHEN CASE_TOTAL_NET_HANDLING_TIME_MINUTES < 30 THEN '10 - 30'
WHEN CASE_TOTAL_NET_HANDLING_TIME_MINUTES < 60 THEN '30 - 60'
ELSE '60+'
END;

-- vii Move this to POWERBI for VISUALIZATION